// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Ben
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

// DejaVu Sans subset covering Greek, Cyrillic, Arabic, and the Arabic
// presentation forms produced by LVGL's contextual shaper.
// Size: 16px, Bpp: 4. Generated by scripts/generate_keyboard_layout_font.sh.
extern const lv_font_t keyboard_layout_font;

#ifdef __cplusplus
}
#endif
